---
kind: pipeline
type: docker
name: default

steps:
  - name: Install Dependancies
    image: python:3.9
    commands:
      - pip install flake8 pytest
      - pip install -r requirements_dev.txt
      - make fmt
      - make lint
      - make test
